# Generated by Django 4.2 on 2023-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_category_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('DL', 'Detergent Laundry'), ('AN', 'Anti Noda'), ('PL', 'Pelengkap Laundry'), ('ML', 'Mesin Laundry')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
